import { Router } from 'express';
import { auth, requireRole } from '../middlewares/auth.js';
import { createCrop, listCrops, getCrop, updateCrop, deleteCrop } from '../controllers/crop.controller.js';
const router = Router();
router.get('/', listCrops);
router.get('/:id', getCrop);
router.post('/', auth, requireRole('farmer'), createCrop);
router.put('/:id', auth, requireRole('farmer'), updateCrop);
router.delete('/:id', auth, requireRole('farmer'), deleteCrop);
export default router;
